### ISSUE TITLE
add contributors

### ISSUE THREAD

**Issue by Tikam02** [Tikam02/AcadVault#26]
@all-contributors please add @Kartikeya99  for projectManagement

**Comment by Tikam02** [comment]
@all-contributors please add @Kartikeya99 for projectManagement

**Comment by Tikam02** [comment]
@all-contributors please add @meet59patel  for contents

**Comment by Tikam02** [comment]
@all-contributors please add @meet59patel for content

**Comment by Tikam02** [comment]
@all-contributors please add @smit2k14  for projectManagement

**Comment by statebait** [comment]
@all-contributors please add @Tikam02 for maintenance

**Comment by Tikam02** [comment]
@all-contributors please add @Kartikeya99 for projectManagement

**Comment by Tikam02** [comment]
@all-contributors please add @statebait  for projectManagement, maintenance

**Comment by Tikam02** [comment]
@all-contributors please add @gauravsofat  for projectManagement

**Comment by statebait** [comment]
@all-contributors please add @Tikam02 for Maintenance, Content, Documentation and projectManagement

**Comment by statebait** [comment]
@all-contributors please add @gauravsofat for Maintenance, Content, Documentation and projectManagement

**Comment by statebait** [comment]
@all-contributors please add @Kartikeya99 for Maintenance, Content, Documentation and projectManagement

**Comment by statebait** [comment]
@all-contributors please add @Kartikeya99 for Maintenance, Content, Documentation and projectManagement

**Comment by statebait** [comment]
@all-contributors please add @smit2k14 for Maintenance, Content, Documentation and projectManagement

**Comment by statebait** [comment]
@all-contributors please add @statebait  for Maintenance, Content, Documentation and projectManagement

**Comment by Tikam02** [comment]
@Vishu26 - Shrikumar
@purva98 - purva

**Comment by statebait** [comment]
@all-contributors please add @Vishu26 for Content

**Comment by statebait** [comment]
@all-contributors please add @purva98 for Content

**Comment by Tikam02** [comment]
@meet59patel  - meet patel
@RoneelV  - content

**Comment by statebait** [comment]
@all-contributors please add @RoneelV for Content

**Comment by statebait** [comment]
@all-contributors please add @meet59patel for Content

**Comment by smit2k14** [comment]
Close this issue now?
