### ISSUE TITLE
Suggestion to upscale and formalise project

### ISSUE THREAD

**Issue by gauravsofat** [Tikam02/AcadVault#4]
Hey, loved the project idea (also the logo 💯). Clearly, this project can help many students if leveraged in a proper manner.
The usefulness of this project depends on two factors viz. the number of contributors and number of users. The project needs visibility to increase both these numbers. Also, as of now the contributing guidelines does not have a formalised submission workflow which could lead to unwanted discrepancies and duplications in the future. 
Accordingly, I suggest that this project be developed in collaboration with @ossdaiict so that it can be maintained as a live project which could be managed by DSC (or external maintainers) in the future. I believe that the org can also be used to promote the project so that it finds maximum contributors.

cc @statebait @smit2k14 @Kartikeya99  
Is this a good/feasible idea?

**Comment by smit2k14** [comment]
Might be that if institute finds out, then we might be penalized. So, haven't yet thought of making it available. Although the OSS thing is a good idea. Might work out

**Comment by statebait** [comment]
I don't have an idea of the implications on making this official under @ossdaiict hence I think we should hold that thought. Other than that, this is great idea @gauravsofat and I'll spread the word for people to contribute to it in an unofficial capacity.

**Comment by Tikam02** [comment]
@gauravsofat @statebait @smit2k14 It's open for you all,make the guidelines do changes and organise the contents.
I'll add you all as maintainer of the repo. 
Also for the contributors list I have already added contributor bot.

**Comment by Kartikeya99** [comment]
This seems to be actually a great idea. @statebait @smit2k14 @gauravsofat Isn't it that though the questions are theirs, the solutions are ours and owned by us and we have the right to make the solutions open source and make it such that people have open access to it? I'm not sure about the collaboration with OSS but we definitely can contribute and make it active.
@Tikam02 yes sounds a great idea to make us maintainers.
I can work on a draft for contribution guidelines and readme and share with you guys.

**Comment by Tikam02** [comment]
I have invited you all, accept the invitations.
And if you have any suggestions for uploading size limit as @smit2k14 has uploaded the ML course content which were really great but size is large, it takes time while cloning or downloading.
@Kartikeya99 initiate the guideline and we'll make improvements.

**Comment by smit2k14** [comment]
Can we drop a mail about this to the students? If not, let's circulate this is students' whatsapp group.

**Comment by gauravsofat** [comment]
Closing this issue in lieu of continuing this conversation on another platform.
