### ISSUE TITLE
Need User Interface - Website

### ISSUE THREAD

**Issue by Tikam02** [Tikam02/AcadVault#61]
## Website to download the contents
 - Good UI/UX
 - Organized contents with directory 
 - Downloadable 
 - User can upload contents through website

**Comment by Tikam02** [comment]
@smit2k14 @Kartikeya99 @statebait we can use this issue for DSC SLOP project.

CC - @abhinavraj23 @hitgo00 @gauravsofat

**Comment by statebait** [comment]
@Tikam02 we should make another repo for the website. Just cloning this repo takes a decent amount of time because of the size.

**Comment by Tikam02** [comment]
@statebait yeah we can make another repo but if it's size will increase then that repo will also take time to clone.
So what if we can create a simple website to download things individually, then we don't have to clone the whole repo.
Just download specific course or contents inside it.

**Comment by statebait** [comment]
The website repo will only have the code for the website which will access
this repo via GitHub's API

**Comment by gauravsofat** [comment]
Agree with @statebait here regarding separation of repos. 
Would be great if someone from DSC takes this up as a SLOP project. We can mentor and help with UI integration, if needed.

**Comment by Tikam02** [comment]
https://github.com/Tikam02/Vault-web

If needed we can host/move this repo in DSC org repo.
@statebait @gauravsofat ???

**Comment by gauravsofat** [comment]
Yes, we should do that – it'll help officiate things a bit and if it becomes a DSC-thing we might see a surge in users/contributors too. 
@Kartikeya99 and @smit2k14 what do you think? I remember you mentioning some concerns with moving this repo to DSC.

**Comment by gauravsofat** [comment]
@Tikam02 has set up a new repo [here](https://github.com/Tikam02/AcadVault-ui)
Closing this issue. Any further discussions/queries about the interface must be taken up in the linked repo.
