### ISSUE TITLE
Issue while cloning the repository.

### ISSUE THREAD

**Issue by Harsh62004** [Tikam02/AcadVault#83]
I am getting the following error while cloning the repository to my local computer.
Please look into it.
![Screenshot (445)](https://user-images.githubusercontent.com/94214306/226562260-cfcecb8b-10dc-46d0-b0ad-f4f811297205.png)

**Comment by MihirKohli** [comment]
[](url)No issues faced while cloning repo.
Try cleaning up workspace
<img width="1097" alt="Screenshot 2023-05-13 at 3 13 19 PM" src="https://github.com/Tikam02/AcadVault/assets/55236890/e2248f0b-bd14-4b8c-be94-e764774d537a">

**Comment by Harsh62004** [comment]
In mac it works, but in windows it is not working because the file type is different.
